services:
  bab:
    image: bab
    build:
      secrets:
        - npmrc
      context: .
    restart: unless-stopped
    init: true
    environment:
      DATABASE_URL: postgresql://postgres@database:5432/postgres?schema=bab
    configs:
      - source: local-json
        target: /app/config/local.json
    volumes:
      - logs:/app/logs
    depends_on:
      - database

  database:
    image: postgres:17.4-alpine3.21
    restart: unless-stopped
    init: true
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      # Network is isolated, who cares
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

secrets:
  npmrc:
    file: $HOME/.npmrc

volumes:
  logs:
  database:

configs:
  local-json:
    content: |
      {
        "server": {
          "publicUrl": "https://bab.alexkar598.dev",
          "host": "0.0.0.0",
          "proxy": false
        },
        "database": {
          "connectionString": "postgresql://postgres@database:5432/postgres?schema=bab"
        },
        "logging": {
          "http": {
            "meta": false
          },
          "file": {
            "enabled": true
          },
          "file-err": {
            "enabled": true
          }
        }
      }