-- AlterTable
ALTER TABLE "Authorization" ALTER COLUMN "startDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "byondState" DROP DEFAULT;

-- AlterTable
ALTER TABLE "ByondCert" ALTER COLUMN "encodedCert" DROP DEFAULT,
ALTER COLUMN "createdTime" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "SigningKey" ALTER COLUMN "createdTime" SET DEFAULT CURRENT_TIMESTAMP;

-- Manual edits
DROP EXTENSION "pgcrypto";